### PR TITLE
Make text color of selected day and current day styleable

### PR DESCRIPTION
**Pull request by SimonStefan**
As mentioned in #166 I've added attributes to style the text colors in the same ways as the circle.
What else do you need to get this Pull Request approved?

### CODE REVIEW

**Comment by SundeepK** [comment]
Thank you for the pull request, will have a look on the coming weekend. By any chance, do you have a nexus 6p? If you do, you can run the screenshot tests using:

`./gradlew verifyMode screenshotTests`

If you use a emulator or a different phone, these tests will likely fail because it looks like a limitation with the facebook-android-screenshot library. I recently discovered this with a previous pull request. But your welcome to try and see if you can run the tests with a nexus 6p emulator and check if they pass. At some point soon I'll regenerate these screenshots using an emulator so that anyone can run against them. If not, don't worry about it. These tests can be found here if your interested:

https://github.com/SundeepK/CompactCalendarView/blob/master/sample/src/androidTest/java/sundeepk/github/com/sample/ApplicationTest.java

Regular tests can run using:

'/.gradlew test`

**Comment by wowlocal** [comment]
I added a color for text of current day by following this steps:

1. Make new attribute in attrs
image

2. Define it on CompactCalendarController
image

3. Some edits on CompactCalendarController (drawMonth)
image

**Comment by nikolleto** [comment]
Can you please review and merge this pull request? I need this feature too.

**Comment by SundeepK** [comment]
I've added some extra commits onto a branch with your changes. I'll be merging the changes to master soon and I'll let you know once the changes are released.

**Comment by SundeepK** [comment]
Released in:
```gradle
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:2.0.2'
}
```

Please allow some time for it to be available.

**Comment by SimonStefan** [comment]
Thank you! I've tried to run the screenshot task, but pullScreenshots failed with
`RuntimeError: ANDROID_SDK or ANDROID_HOME needs to be set`

It seems that python doesn't get my ANDROID_HOME environment variable

**Comment by nikolleto** [comment]
@SundeepK Thank you so much! I'm already using this new feature.

**Comment by SundeepK** [comment]
@SimonStefan that because you need to set the environment variable set to your android sdk. I should add it in the readme for future developers who want to send pull requests. It required by facebook screenshot tests. But thank you for the pull request.

**Pull request merged**
