### PR TITLE
Don't select first day on month scroll - added property

### PR DESCRIPTION
**Pull request by jklp**
Hi, this was bugging me for awhile, but I've added a new property (compactCalendarSelectFirstDayOfMonthOnScroll) which when set to false (by default it's true), won't automatically change the selected date to the first day of the newly selected month.

### CODE REVIEW

**Comment by samerzmd** [comment]
was just thinking about it  :+1:

**Comment by SundeepK** [comment]
Sorry for the delayed reply. I've been on holiday so I havnt had time to looks at pull requests. I would have merged straight. But I have another branch which has implemented smooth-scrolling and opening/closing the calendar. This is a big refactoring of the current code.

So I'll have to decide if I should apply these before or after I merge the other branch. Either way, there will be merge conflicts. I'm leaning on merging the other branch and then going through pull requests.

**Comment by jklp** [comment]
Ah actually I might cancel this PR ... while testing I noticed that a couple of things are broken, like changing to the next/previous months etc ... though would still be good to have a feature like this

**Comment by SundeepK** [comment]
Gonna go ahead and close this. There is an issue raised for this and I'll get around to it soon - I hope.

**Pull request closed without merging**
