### PR TITLE
The minSdkVersion can be adjusted to 11

### PR DESCRIPTION
**Pull request by Saxxhw**

### CODE REVIEW

**Comment by luizfp** [comment]
Please, accept this PR.

**Comment by SundeepK** [comment]
Thanks, forgot about this improvement. I'll do some testing this weekend by pulling in the changes and making sure nothing breaks. If all clear, i'll merge the change.

**Comment by luizfp** [comment]
I forked and tested here as well. Everything seems to works fine. Waiting for the merge. Thanks!!!
:+1:

**Comment by luizfp** [comment]
Hi, did you find any problems with minSdkVersion 11? I would be glad to help.

**Comment by SundeepK** [comment]
Sorry for being so slow. I'm releasing a new version now will update this pull request and readme shortly.

**Comment by luizfp** [comment]
No problem. Thanks!!! :)

**Comment by SundeepK** [comment]
```gradle
dependencies {
    compile 'com.github.sundeepk:compact-calendar-view:2.0.2.1'
}
```

**Comment by SundeepK** [comment]
Please allow some time for it to be available.

**Pull request merged**
