### PR TITLE
TextColor for the selected Day and current day

### PR DESCRIPTION
**Pull request by samerzmd**
thanks for the amazing component.
i needed these two features Text Color for the current Day and for the current selected day,
so i have implemented them and thought why not to share the code :)

### CODE REVIEW

**Comment by SundeepK** [comment]
Hi thanks for the PR. I havn't looked through the changes througly. But I have another branch which implements smooth-scrolling and open/close the calendar. 

https://github.com/SundeepK/CompactCalendarView/tree/%40wip/exprimental_animation

It's 51 commits ahead of master. I think your changes should sit well, but I will need to either merge the other branch and then this code or vise versa. I'll have a look sometime this week and keep you posted.

**Comment by samerzmd** [comment]
got you, if any help needed ping me.
thanks for your effort :)>-

**Comment by SundeepK** [comment]
Hi, as mentioned before, I've merged my changes to master now. I can have a look at this PR some time soon. But if you have time, you can clone the latest code and apply your changes on top. Might want to send a seperate PR for that so that commit history is cleaner.

**Comment by samerzmd** [comment]
will do it in the next few days

**Comment by samerzmd** [comment]
will rebase and PR again (y)

**Pull request closed without merging**
